### ISSUE TITLE
semaphore не собирается

### ISSUE THREAD

**Issue by eugenevlasov** [MarkuSasen/OSLabs#1]
gcc -o exe main.c -lpthread #-std=c11 -_XOPEN_SOURCE
main.c:136:84: error: no member named '__key' in 'struct ipc_perm'; did you mean '_key'?
                                shmcurrentinfo.shm_segsz,  shmcurrentinfo.shm_perm.__key,
                                                                                   ^~~~~
                                                                                   _key
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/ipc.h:114:18: note: '_key' declared here
        key_t           _key;           /* Reserved for internal use */
                        ^
main.c:179:33: warning: 'sem_getvalue' is deprecated [-Wdeprecated-declarations]
                                sem_getvalue(sema, &sval);
                                ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/semaphore.h:54:56: note: 'sem_getvalue' has been explicitly marked deprecated here
int sem_getvalue(sem_t * __restrict, int * __restrict) __deprecated;
                                                       ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:187:40: note: expanded from macro '__deprecated'
#define __deprecated    __attribute__((__deprecated__))
                                       ^
main.c:216:30: warning: format string contains '\0' within the string body [-Wformat]
        sprintf(buf, "%s : %d\0", buf, getpid());
                     ~~~~~~~~^~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/secure/_stdio.h:47:56: note: expanded from macro 'sprintf'
  __builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)
                                                       ^~~~~~~~~~~
2 warnings and 1 error generated.
make: *** [all] Error 1

**Comment by MarkuSasen** [comment]
На некоторых системах, структура имеет поле __key, a не _key. Исправлено.
